# Generated by Django 6.1 on 2026-08-20 02:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('inner_length', models.DecimalField(decimal_places=2, help_text='Internal length in cm.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('inner_width', models.DecimalField(decimal_places=2, help_text='Internal width in cm.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('inner_height', models.DecimalField(decimal_places=2, help_text='Internal height in cm.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum load in kg.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('cost', models.DecimalField(decimal_places=2, help_text='Unit cost of the box.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Only active boxes are considered for selection.')),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('length', models.DecimalField(decimal_places=2, help_text='cm', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='cm', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='cm', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('weight', models.DecimalField(decimal_places=3, help_text='kg', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
